apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e2e-tests-go-akamtuoe
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/e2e-tests-go-akamtuoe:536d2fdbfa6e27451da888e67e4d653332cf2530
          name: container-image
